### ISSUE TITLE
Increase polling cycle for LivenessProbe for WMCore services

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#10223]
**Impact of the new feature**
WMCore central services

**Is your feature request related to a problem? Please describe.**
Not really a problem, but I don't think we need to ping our service every 10 seconds, which generates a log record.
WMCore services (almost) never need any kick/restart, so we can relax it a bit and have less pollution of the service logs.

**Describe the solution you'd like**
We should review the Livenessprobe configuration for ALL WMCore services and set those values to a more realistic value (otherwise we risk having our services getting incorrectly restarted). Here is an example of configuration:
https://github.com/dmwm/CMSKubernetes/blob/master/kubernetes/cmsweb/services/reqmgr2.yaml#L106

giving special attention to:
* `periodSeconds`: 30: will execute that call every 30 seconds
* `timeoutSeconds`: 10: if no answer is received in 10 seconds, the call is considered as failed. Three (3) consecutive failures trigger a service restart.
* and the API used to test the service (see further details in https://github.com/dmwm/WMCore/issues/11262)

This has to be changed to every single WMCore service.

**Describe alternatives you've considered**
not do anything

**Additional context**
none

**Comment by amaltaro** [comment]
I am adding this issue to our Q3/2022 queue (and boosting it to high priority). It should be pretty straight forward and will make any future k8s debugging easier.

As mentioned in the initial description, we should review the Livenessprobe configuration for ALL WMCore services and set those values to a more realistic value (otherwise we risk having our services getting incorrectly restarted). Here is an example of configuration:
https://github.com/dmwm/CMSKubernetes/blob/master/kubernetes/cmsweb/services/reqmgr2.yaml#L106-L117

giving special attention to:
* `periodSeconds: 30`: will execute that call every 30 seconds
* `timeoutSeconds: 10`: if no answer is received in 10 seconds, the call is considered as failed.
3 consecutive failures trigger a service restart.

The outcome should be a PR against the CMSKubernetes repository with an update to those values. In general, I do not think we need to have a polling cycle smaller than 30secs.

**Comment by vkuznet** [comment]
@amaltaro , in order to implement the proper policy someone with expertise should provide full list of appropriate values based on knowledge of the system, workflows, load, etc. I suggest that we list each individual system and add next to it current and new values, e.g.

ReqMgr2 service
- current policies:
```
        resources:
          requests:
            memory: "512Mi"
            cpu: "200m"
          limits:
            memory: "3Gi"
            cpu: "1000m"
```
new policies: ....
- current liveness prove
```
        livenessProbe:
          exec:
            command:
            - cmsweb-ping
            - "--url=http://localhost:8246/reqmgr2/data/info"
            - "--authz=/etc/hmac/hmac"
            - -verbose
            - "0"
          initialDelaySeconds: 120
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 10
```
new livenessprobe policies ...

Please note that for livenessprobe we need one API which should be used to test the service. This API can be light or (semi)-heavy. For instance, for a service which has access to DB you need to decide if API should only response to HTTP request or should it query the DB, if later is the case the query of DB should **represent** that service is operating normally. For example, for DBS liveness prove I use `/healthz` API, this API query DBS DB and fetches data from smallest table, e.g. data-tiers. As such when k8s liveness probe call `/healthz` API I'm sure that DBS HTTP server is working (the API should return 200 OK) and DBS DB is working properly (since I query some table, I also check that return result has meaningful values, e.g. RAW data-tier is present in response). As such this `/healthz` API guarantees that call to DBS represent working system.

Therefore, I suggest to break down this issue into different ones:
- one to check resources polices
- one to check liveness probes
- one to design/adjust/set liveness probe API

All three are important on k8s and should be fast enough to tell k8s the whole story about the service.
