### ISSUE TITLE
large delay in file injection

### ISSUE THREAD

**Issue by vlimant** [dmwm/WMCore#9543]
**Impact of the bug**
workflows are ending in completed with missing files/statistics. talked about this to @amaltaro who did not have time to put this on anyone's radar before leaving apparently

**Describe the bug**
workflow are getting in "completed" while files are still being injected

**How to reproduce it**
https://cmsweb.cern.ch/reqmgr2/fetch?rid=cmsunified_ACDC0_task_EXO-RunIIFall17wmLHEGS-02448__v1_T_200211_194626_1071
https://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?prep_id=task_EXO-RunIIFall17wmLHEGS-02448

and many others in "filemismatch" under https://cms-unified.web.cern.ch/cms-unified//assistance.html are likely affected

**Expected behavior**
#8148 for example

**Comment by todor-ivanov** [comment]
@vlimant Thanks for reporting it. I am looking at the issue now. May come back with further questions later, though.

**Comment by todor-ivanov** [comment]
I still do not have the reason why it happens, but would like to add some more info regarding the consequences of that. For the workflow in question: It is a an ACDC and the original request is this one: 
https://cmsweb.cern.ch/reqmgr2/fetch?rid=pdmvserv_task_EXO-RunIIFall17wmLHEGS-02448__v1_T_191031_011220_8129

Checking the number of events in the request and the numbers (both events and files) in the Output datasets there is some difference :

```
----------------------------------------------------
==> pdmvserv_task_EXO-RunIIFall17wmLHEGS-02448__v1_T_191031_011220_8129
----------------------------------------------------

|***************************************************|
|                         | CouchDB | PhEDEx | DBS  |
|---------------------------------------------------|
| Same dataset name       | ok      | ok     | ok   |
| Same dataset size       | NOPE    | NOPE   | NOPE | 
| Same number of blocks   | --      | ok     | ok   |
| Same number of files    | NOPE    | NOPE   | NOPE | 
| Same number of events   | NOPE    | --     | NOPE |
| Same number of lumis    | ok      | --     | ok   |
| Same PhEDEx Node Name   | --      | NOPE   | NOPE |
|***************************************************|

======> Request information from reqmgr2 db: 
    InputDataset: 
    RequestNumEvents: 50000
    Runtime: 2439.70333333
    TotalEstimatedJobs: 13
    TotalInputEvents: 50000
    TotalInputFiles: 0
    TotalInputLumis: 50
    lumis: 50
...
======> Couch output dataset info: 
    /LQToBMu_M-1000_single_TuneCP2_PSweights_13TeV-madgraph-pythia8/RunIIFall17MiniAODv2-PU2017_12Apr2018_94X_mc2017_realistic_v14-v1/MINIAODSIM: 
        dsetSize: 3084801131
        events: 46000
        numFiles: 7
...
======> DBS info: 
    /LQToBMu_M-1000_single_TuneCP2_PSweights_13TeV-madgraph-pythia8/RunIIFall17MiniAODv2-PU2017_12Apr2018_94X_mc2017_realistic_v14-v1/MINIAODSIM: 
        dsetSize: 3361332847
        events: 50000
        lumis: 50
        numBlocks: 8
        numFiles: 8
        prep_id: EXO-RunIIFall17MiniAODv2-03804
...
======> PhEDEx info: 
    /LQToBMu_M-1000_single_TuneCP2_PSweights_13TeV-madgraph-pythia8/RunIIFall17MiniAODv2-PU2017_12Apr2018_94X_mc2017_realistic_v14-v1/MINIAODSIM: 
        dsetSize: 3361332847
        numBlocks: 8
        numFiles: 8
```

Obviously DBS and Phedex are in agreement for the number of files while couchdb is having some discrepancy. Then querying couchdb about the ACDC clearly shows that the ACDC covered the event deficit and the missing file is there:

```
    output: 
        /LQToBMu_M-1000_single_TuneCP2_PSweights_13TeV-madgraph-pythia8/RunIIFall17MiniAODv2-PU2017_12Apr2018_94X_mc2017_realistic_v14-v1/MINIAODSIM: 
            events: 4000
            nFiles: 1
            size: 276531716
            tasks: 
                /cmsunified_ACDC0_task_EXO-RunIIFall17wmLHEGS-02448__v1_T_200211_194626_1071/EXO-RunIIFall17DRPremix-03855_0/EXO-RunIIFall17DRPremix-03855_1/EXO-RunIIFall17MiniAODv2-03804_0/EXO-RunIIFall17MiniAODv2-03804_0MergeMINIAODSIMoutput
```
Obviously due to the delayed injection of the files (after the workflow has been completed) Couchdb is not updating the information about the output. But at least the requested number of events are present.
